// Operational — jobs, state machine, certifications, RFQs, quotes
//
// Part of the Clarent Drizzle schema. See schema/index.ts for the
// full export surface. SQL migrations live in supabase/migrations/
// and are applied via the Supabase CLI.

import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

import {
  generators,
  generatorLocations,
  generatorContacts,
  vendors,
  wasteFrameworkEnum,
} from './core';

// ============================================================================
// Group 3 — Operational: jobs, state machine, certifications, RFQs, quotes
// ============================================================================

// ----------------------------------------------------------------------------
// Operational enums
// ----------------------------------------------------------------------------

// One job state machine governs every workflow (see plan guiding principles).
// Never bypass. Transitions happen in lib/workflow/.
export const jobStateEnum = pgEnum('job_state', [
  'draft', // intake in progress
  'classified_standard', // Lane 1 — confident, instant-price eligible
  'classified_complex', // Lane 2 — needs ops review + RFQ
  'priced', // price set, awaiting customer acceptance
  'quote_sent', // quote delivered to generator
  'quote_accepted', // generator accepted terms
  'advance_paid', // deposit received (Stripe webhook)
  'vendor_selected', // ops or auto-router has chosen a vendor
  'vendor_notified', // work order sent to vendor
  'pickup_scheduled', // vendor confirmed date
  'balance_due', // balance invoice issued
  'balance_paid', // generator paid balance
  'pickup_completed', // vendor confirmed waste removed
  'documents_processing', // manifests / CoD pending
  'completed', // all docs filed, payouts scheduled
  'non_compliant_flagged', // vendor reported non-compliant waste
  'disputed', // disagreement between parties
  'cancelled', // cancelled before pickup
  'refunded', // cancelled after payment
]);

export const jobLaneEnum = pgEnum('job_lane', ['lane_1', 'lane_2']);

export const rfqStateEnum = pgEnum('rfq_state', ['open', 'closed', 'awarded', 'cancelled']);

export const rfqRecipientStateEnum = pgEnum('rfq_recipient_state', [
  'pending',
  'opened',
  'responded',
  'declined',
  'expired',
]);

export const quoteStateEnum = pgEnum('quote_state', [
  'draft',
  'sent',
  'accepted',
  'rejected',
  'expired',
  'superseded',
]);

// ----------------------------------------------------------------------------
// Jobs — central operational record
// ----------------------------------------------------------------------------

export const jobs = pgTable(
  'jobs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    // Human-friendly reference like "CLR-2026-0001". Generated by app layer.
    referenceNumber: text('reference_number').notNull(),
    generatorId: uuid('generator_id')
      .notNull()
      .references(() => generators.id, { onDelete: 'restrict' }),
    generatorLocationId: uuid('generator_location_id')
      .notNull()
      .references(() => generatorLocations.id, { onDelete: 'restrict' }),
    generatorContactId: uuid('generator_contact_id').references(() => generatorContacts.id, {
      onDelete: 'set null',
    }),
    state: jobStateEnum('state').notNull().default('draft'),
    lane: jobLaneEnum('lane'),
    wasteFramework: wasteFrameworkEnum('waste_framework'),
    classificationConfidence: numeric('classification_confidence', { precision: 5, scale: 2 }),
    // Requested by generator during intake
    requestedPickupWindow: text('requested_pickup_window'),
    // Confirmed by vendor
    scheduledPickupDate: timestamp('scheduled_pickup_date', { withTimezone: true }),
    actualPickupDate: timestamp('actual_pickup_date', { withTimezone: true }),
    // Financial snapshot (sourced from quotes/invoices; cached for querying)
    estimatedTotal: numeric('estimated_total', { precision: 12, scale: 2 }),
    finalTotal: numeric('final_total', { precision: 12, scale: 2 }),
    depositAmount: numeric('deposit_amount', { precision: 12, scale: 2 }),
    balanceAmount: numeric('balance_amount', { precision: 12, scale: 2 }),
    selectedVendorId: uuid('selected_vendor_id').references(() => vendors.id, {
      onDelete: 'set null',
    }),
    // Flags surface exception queue items (non_compliant, disputed, stale, etc)
    flags: text('flags').array(),
    notes: text('notes'),
    // When the state machine most recently changed (for stale-job detection)
    stateChangedAt: timestamp('state_changed_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('jobs_reference_number_key').on(t.referenceNumber),
    index('jobs_generator_id_idx').on(t.generatorId),
    index('jobs_generator_location_id_idx').on(t.generatorLocationId),
    index('jobs_selected_vendor_id_idx').on(t.selectedVendorId),
    index('jobs_state_idx').on(t.state),
    index('jobs_lane_idx').on(t.lane),
    index('jobs_state_changed_at_idx').on(t.stateChangedAt),
    index('jobs_created_at_idx').on(t.createdAt),
  ],
);

// ----------------------------------------------------------------------------
// Job waste streams — a job can have multiple streams (future-proof;
// Phase 3 MVP creates one per job, but the schema supports bundles)
// ----------------------------------------------------------------------------

export const jobWasteStreams = pgTable(
  'job_waste_streams',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    jobId: uuid('job_id')
      .notNull()
      .references(() => jobs.id, { onDelete: 'cascade' }),
    // FK to waste_streams reference table will come in Group 2; for now text key
    wasteStreamKey: text('waste_stream_key').notNull(),
    wasteCodePrefixes: text('waste_code_prefixes').array(),
    containerType: text('container_type').notNull(),
    containerCount: integer('container_count').notNull(),
    estimatedWeightLbs: numeric('estimated_weight_lbs', { precision: 10, scale: 2 }),
    // Generator-reported condition; triggers Lane 2 if not 'intact'
    containerCondition: text('container_condition'),
    unContainerCertified: boolean('un_container_certified').notNull().default(false),
    notes: text('notes'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('job_waste_streams_job_id_idx').on(t.jobId),
    index('job_waste_streams_waste_stream_key_idx').on(t.wasteStreamKey),
  ],
);

// ----------------------------------------------------------------------------
// Certifications — timestamped generator affirmations per intake
// ----------------------------------------------------------------------------

export const certifications = pgTable(
  'certifications',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    jobId: uuid('job_id')
      .notNull()
      .references(() => jobs.id, { onDelete: 'restrict' }),
    generatorId: uuid('generator_id')
      .notNull()
      .references(() => generators.id, { onDelete: 'restrict' }),
    generatorContactId: uuid('generator_contact_id').references(() => generatorContacts.id, {
      onDelete: 'set null',
    }),
    // Template version so we can evolve certification language without
    // breaking historical records
    templateVersion: integer('template_version').notNull(),
    // Full payload: affirmations (array of {key, value}), signer info, rendered text
    payload: jsonb('payload').notNull(),
    signedAt: timestamp('signed_at', { withTimezone: true }).notNull().defaultNow(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('certifications_job_id_idx').on(t.jobId),
    index('certifications_generator_id_idx').on(t.generatorId),
    index('certifications_signed_at_idx').on(t.signedAt),
  ],
);

// ----------------------------------------------------------------------------
// RFQs — anonymized solicitations sent to vendors
// ----------------------------------------------------------------------------

export const rfqs = pgTable(
  'rfqs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    jobId: uuid('job_id')
      .notNull()
      .references(() => jobs.id, { onDelete: 'cascade' }),
    referenceNumber: text('reference_number').notNull(),
    // Everything a vendor sees pre-award (sanitized: no generator identity,
    // only a geographic zone). Captured as jsonb for auditability and replay.
    anonymizedPayload: jsonb('anonymized_payload').notNull(),
    state: rfqStateEnum('state').notNull().default('open'),
    responseDeadlineAt: timestamp('response_deadline_at', { withTimezone: true }).notNull(),
    awardedVendorQuoteId: uuid('awarded_vendor_quote_id'),
    awardedAt: timestamp('awarded_at', { withTimezone: true }),
    closedAt: timestamp('closed_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('rfqs_reference_number_key').on(t.referenceNumber),
    index('rfqs_job_id_idx').on(t.jobId),
    index('rfqs_state_idx').on(t.state),
    index('rfqs_response_deadline_at_idx').on(t.responseDeadlineAt),
  ],
);

// ----------------------------------------------------------------------------
// RFQ recipients — which vendors received each RFQ and their response state
// ----------------------------------------------------------------------------

export const rfqRecipients = pgTable(
  'rfq_recipients',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    rfqId: uuid('rfq_id')
      .notNull()
      .references(() => rfqs.id, { onDelete: 'cascade' }),
    vendorId: uuid('vendor_id')
      .notNull()
      .references(() => vendors.id, { onDelete: 'restrict' }),
    state: rfqRecipientStateEnum('state').notNull().default('pending'),
    notifiedAt: timestamp('notified_at', { withTimezone: true }).notNull().defaultNow(),
    openedAt: timestamp('opened_at', { withTimezone: true }),
    respondedAt: timestamp('responded_at', { withTimezone: true }),
    declineReason: text('decline_reason'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('rfq_recipients_rfq_vendor_key').on(t.rfqId, t.vendorId),
    index('rfq_recipients_vendor_id_idx').on(t.vendorId),
    index('rfq_recipients_state_idx').on(t.state),
  ],
);

// ----------------------------------------------------------------------------
// Vendor quotes — vendor pricing responses to an RFQ
// ----------------------------------------------------------------------------

export const vendorQuotes = pgTable(
  'vendor_quotes',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    rfqId: uuid('rfq_id')
      .notNull()
      .references(() => rfqs.id, { onDelete: 'cascade' }),
    rfqRecipientId: uuid('rfq_recipient_id')
      .notNull()
      .references(() => rfqRecipients.id, { onDelete: 'cascade' }),
    vendorId: uuid('vendor_id')
      .notNull()
      .references(() => vendors.id, { onDelete: 'restrict' }),
    perUnitPrice: numeric('per_unit_price', { precision: 12, scale: 2 }),
    minimumJobCharge: numeric('minimum_job_charge', { precision: 12, scale: 2 }),
    stopFee: numeric('stop_fee', { precision: 12, scale: 2 }),
    fuelSurcharge: numeric('fuel_surcharge', { precision: 12, scale: 2 }),
    otherFees: numeric('other_fees', { precision: 12, scale: 2 }),
    totalEstimate: numeric('total_estimate', { precision: 12, scale: 2 }).notNull(),
    earliestPickupDate: date('earliest_pickup_date'),
    conditions: text('conditions'),
    // Structured line items for richer display/audit
    lineItems: jsonb('line_items'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('vendor_quotes_recipient_key').on(t.rfqRecipientId),
    index('vendor_quotes_rfq_id_idx').on(t.rfqId),
    index('vendor_quotes_vendor_id_idx').on(t.vendorId),
  ],
);
export const quotes = pgTable(
  'quotes',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    jobId: uuid('job_id')
      .notNull()
      .references(() => jobs.id, { onDelete: 'cascade' }),
    // Lane 2 quotes derive from a chosen vendor quote; Lane 1 quotes do not
    vendorQuoteId: uuid('vendor_quote_id').references(() => vendorQuotes.id, {
      onDelete: 'set null',
    }),
    state: quoteStateEnum('state').notNull().default('draft'),
    subtotal: numeric('subtotal', { precision: 12, scale: 2 }).notNull(),
    fees: numeric('fees', { precision: 12, scale: 2 }).notNull().default('0'),
    total: numeric('total', { precision: 12, scale: 2 }).notNull(),
    depositPercent: numeric('deposit_percent', { precision: 5, scale: 2 }).notNull().default('60'),
    lineItems: jsonb('line_items').notNull(),
    termsVersion: integer('terms_version').notNull(),
    validUntil: timestamp('valid_until', { withTimezone: true }).notNull(),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
    rejectedAt: timestamp('rejected_at', { withTimezone: true }),
    rejectionReason: text('rejection_reason'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('quotes_job_id_idx').on(t.jobId),
    index('quotes_state_idx').on(t.state),
    index('quotes_valid_until_idx').on(t.validUntil),
  ],
);
